RocketChat/Rocket.Chat.Electron

app/app.html, app/main.js, app/scripts/start.js
This enables the ability to select the host.
Shows error if the host is not a valid rocket.chat instance.
If they don't enter anything it'll prompt them to connect to the demo instance.  Like so:
I'd like to enable a menu option to take them back to the screen to enter a new url.
=> Enable host selection

app/scripts/start.js
If you first load up the application without ever running it before an error would occur in the console about getting the length of a null variable. This checks to verify that the hosts array isn't null before looping through them. Fixes #30
=> Only loop through hosts if they exists, fixes #30

app/main.js, package.json
Got an error and was unable to start on Ubuntu 14.04.3 LTS.
* Installed vinyl-map and it worked.
* Removed vinyl-map and started getting these errors in terminal although it launched.
* Went away as expected when module was reinstalled.
```
Error: Cannot find module 'vinyl-map'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/home/pauls/Rocket.Chat.Electron/tasks/build.js:9:11)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> …
```
=> add missing vinyl-map requirement

app/scripts/menus.js, app/scripts/tray.js, resources/windows/installer.nsi
Can you review my changes? :)
Commit (1) comment:
- Added a force quit option to the app, if this is set, the application will quit. Otherwise it'll just hide. (#89)
- Fixed bug in windows, where you had to triple-click the tray icon show the app (#77)
Commit (2) comment:
- Added check, if the application is running, because this lead to
errors
- Added option to add a shortcut to the autostart folder (#57)
- Added option to launch the app after the installation (#37)
- Added option to choose the installation directory (#41)
- Added the shortcuts as options, so you can choose, if you want a
desktop, autostart or start menu shortcut (a part of #96)
- Enabled / Added these pages: components, browse installation folder,
finish page
- Extended the comments, so it's easier to find the correct …
=> Fix for some issues (installer & client)

app/background.js, app/vendor/electron_boilerplate/window_state.js
If the client was closed in hidden state, it will also start hidden.
Fixes a part of issue  #96
=> Option to start the client hidden

app/scripts/menus.js
=> Add zoom options

resources/windows/installer.nsi
Closes #200 
This change to the NSIS compilation adds a check for the /silent switch. If this switch exists, the installer installs silently by setting SetSilent to 'silent' (as opposed to the default value 'normal').
=> Close #200; Added /silent switch to the .exe installer

app/background.js, app/notification.html, app/package.json, app/scripts/preload.js, app/scripts/start.js, package.json
@RocketChat/core
@rodrigok 
@geekgonecrazy 
This PR addresses the issue on #199 to restrict the notification for systems with no native support. Now only Windows XP, Vista and 7.
Closes #55.
=> Notifications on Windows XP, Vista, 7

app/scripts/webview.js, package.json
@RocketChat/core
Launch external desktop application on clicked non http url. e.g. `mailto:`, `tel:`
>Open the given external protocol URL in the desktop's default manner. (For example, mailto: URLs in the user's default mail agent.) Returns true if an application was available to open the URL, false otherwise.
See also: [shell.openExternal()](https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl-options)
=> Open external app

README.md
`libxss-dev` is not installed by default on Ubuntu.
=> Note for debian developers

app/package.json, app/scripts/preload.js
- Re-enable previously broken spellchecking code for electron-update
- Fix Mac OS X not having spellchecker module, and thus not working, by adding explicit spellchecker v3.3.1 dependency
- Fixed no default language being selected on Windows when spellchecker loads the available dictionaries (en-US as opposed to en_US)
Tested on so far:
- Windows 10 x64
- Mac OS X Siera (10.12)
- Ubuntu 16.04.1 LTS
- Fedora 25.1
=> electron-update fix spellcheck

resources/linux/RHEL/app.spec, tasks/release/linux.js
Code test pass: http://p.fdzh.org/qjzP2mEl
Need to test rpm package:
Test steps(On Fedora22/23):
1.build rpm and deb
```
$ sudo dnf install dpkg rpm-build npm fakeroot
$ npm install
$ npm run release
```
2.install rpm
```
$ sudo dnf install rocketchat-v1.2.0-linux.x86_64.rpm  # Fedora 22+
$ sudo yum localinstall rocketchat-v1.2.0-linux.x86_64.rpm  # RHEL 7 / Fedora 21-
$ sudo zypper install rocketchat-v1.2.0-linux.x86_64.rpm  # openSUSE
```
=> create rpm package

build/win/installer.nsh, package.json
The default settings for electron-builder's win target aren't great. They create a setup exe that is one-click and automatically installs Rocket.Chat+ into the current users AppData folder with no way to change it. This isn't terribly user friendly and is probably a no-no in some Enterprise environments that use Rocket.Chat. Additionally the created uninstallation entry doesn't have an icon with the default settings. I've changed the build config to do the following:
* Now not one-click, forced to All Users instead like the old installer
* Now shows an icon in Programs and Features instead of being blank
* Now allows changing installation directory
=> Fix various quirks with the windows installer

package.json
Closes #338
When launched the desktop app is iconless and independent from the launcher. This line added to the rocketchat.desktop file ensures the launcher and the app remain as one on the desktop.
=> Fix issues with desktop entry on linux

src/public/preload.js
Closes RocketChat/Rocket.Chat#5046
Fix issue mentioned in #308 
Don't redirect to url/image url if image or url is dragged into window.
Tested, and this doesn't stop drag&drop image upload from working.
=> Stop redirect when dragging image/url into window

src/scripts/tray.js
Closes #353 
tray.js was missing the assignment of the _tray object into the mainWindow.  This caused the code to never modify the tray when showTrayAlert() was called.
=> Fix to put tray object in mainWindow allowing for tray icon alerts to work

src/scripts/webview.js
Closes #385 
Closes #389 
It seems the `did-fail-load` event fires when links such as youtube fail to load, causing the server reload screen to show. This makes it only check for errors in loading the main app.
=> Only show reload screen if main webview error

src/background.js, src/scripts/sidebar.js, src/stylesheets/main.less, src/stylesheets/start-page.less, src/stylesheets/webview/custom.css
Changes to make it look cooler in macOS by removing the titlebar
=> Make it sexier in macOS

package.json, src/public/app.html, src/scripts/menus/window.js, src/scripts/start.js, src/scripts/webview.js, src/stylesheets/main.less, src/stylesheets/start-page.less
Closes #410 
Fixes bug with selecting text by changing drag region show in images below.
Green means it is draggable (meaning you can't highlight text). If you remove the server list it just gets rid of that drag region, and the rest stays the same.
=> Fix bug with highlighting text & drag region on macOS

README.md
This should help a few people, Figured it out on my own and want to share it with everyone.
Super helpful in large deployments.
=> Updated README with servers.json instructions

src/background/autoUpdate.js, src/public/about.html, src/scripts/menus/app.js
Remove dev code to open dev tools, and show a response when user click check for updates, and there are none
=> Don't open dev tools on about, and show message when no updates

src/scripts/servers.js
Closes #455
Loading servers.json file from install location unless a servers.json is placed in user's local config, e.g. in %APPDATA%/Roaming on Windows. Why that? If deploying rocket.chat client with /allusers, a deployment tool in a last step could copy a preconfigured servers.json into the global installation location. If the client is started the server URL is preconfigured to the own server by the global servers.json to any user on the system unless a user overwrites it by an own one.
=> [NEW] check install location for a servers.json as well

src/public/preload.js
Closes #498
Refactor the code so instead of sending a keep alive every 10 seconds, we actually manage user presence status in the app. Every 10 seconds we still check if the user is idle or not, but only call Meteor when we change states.
=> [FIX] Refactor keep-alive to remove excessive calls to UserPresence

src/scripts/menus/app.js
=> Add missing Services menu in application menu on macOS

src/background.custom.js, src/public/lib/Notification.js
FIX #193
`BundleId` is undefined in packaged version which caused wrong App Icon to show up. Also, clicking on the notification now focus back to the App main window.
=> Enhancements to OSX Notifications

src/background.custom.js
Closes #499 #300
The app remembers its previous state, so if you close it minimised then it will open minimised etc. There were a couple of places missing where it saves the state when you restore the window, so after you hide it once, it always open hidden.
=> Fix minimised start on Windows

src/scripts/webview.js
Jitsi meeting url was being saved to the webview, overwriting the server url and making the electron app unusable, only fix was removing the server and adding again (or changing url via DevTools).
This fix should solve that and other possible leaks due to iframe url being saved to the webview.
=> [FIX] Fix for leaking jitsi url to webview

src/scripts/sidebar.js
Closes #214 
this feature introduce the option to drag and drop servers on sidebar, it uses localstorage to save it so when you open the app again it should keep the order
=> [NEW] Adds drag-and-drop on sidebar

src/scripts/tray.js
closes #44 
When minimizing/restoring the window it doesn't fire the "open/close" events,
so if you minimize it and right-click the tray icon you will see "Hide" option (incorrect one),
clicking it won't change anything as the window is already hidden.
=> [NEW] Adds extra validation on minimizing or restoring the window

src/background/windowState.js, src/helpers/window.js
the window size (height/widhth, x/y) should all be integers
if window tried to load with float numbers it was throwing errors
on the main process.
Closes #540
=> [FIX] window-size: fix error on loading screen

snap/snapcraft.yaml
The snap package does not have access to the camera.
Camera is added in the plugs list. The app still needs to be manually connected
after install tough, because the camera interface is not an
`auto-connect` one.
(see https://docs.snapcraft.io/reference/interfaces).
Closes #601
=> [FIX] Add camera plug in snapcraft.yaml

src/scripts/menus.js
refixes #50
Fixes the issue when alt-shift layout switch caused RocketChat menu popup on KDE.
=> [FIX] Add & to menu items to avoid alt-shift menu popup

src/i18n/lang/de_DE.i18n.json, src/i18n/lang/en.i18n.json, src/scripts/menus/view.js
[NEW] Add shortcut to enter full screen on osx.
Add new menu item to the view menu to enter full screen by menu an keyboard shortcut.
(Default option in all osx applications)
=> [NEW] add osx shortcut to enter full screen

src/public/preload.js, src/scripts/sidebar.js, src/scripts/start.js, src/scripts/tray.js, src/scripts/webview.js
Add new feature to show account status in menu bar 
(implemented for all OS - actually there now special icons for windows and linux)
[Feature Request](https://github.com/RocketChat/Rocket.Chat.Electron/issues/703)
[Server Changes to activate function](https://github.com/RocketChat/Rocket.Chat/pull/11303)
Short video about the new feature
=>  [NEW] Show account status in menu bar

package.json
Closes #680
Stumbled upon this while checking out #763 (may collide with this PR) and saw that the definition for Linux targets seems to have changed in electron builder.
With this change the category is set correctly in the `*.desktop` file.
=> [FIX] Correctly use category for Linux targets

src/scripts/start.js, src/scripts/tray.js, src/scripts/webview.js
The pull request fix some issues with the badge and the icon loading on windows.
(every thing works correctly right now on all Platforms like before
[FIX] a bug introduces by the following commit:
[[NEW] Show account status in menu bar #759](https://github.com/RocketChat/Rocket.Chat.Electron/pull/759)
There some points still open:
- Creating status icon's for Windows and Linux (I will create one soon) to follow the other discussions pls see: [discussion](https://github.com/RocketChat/Rocket.Chat.Electron/pull/759)
sorry i closed: [768](https://github.com/RocketChat/Rocket.Chat.Electron/pull/768)
=> [FIX] User status badge and icon visualisation

src/scripts/start.js
Closes #794
Adapted the code to always update the badge with either the number of unread highlights (priority) or the existing old notification title (for the "dot" notification in case there are no highlights but activity).
=> [FIX] for #794 macOS dock badge not clearing anymore

src/public/jitsi-preload.js
Right now when you try to share your screen it opens a developer window.
=> FIX: Remove developer debug window during screen share

src/public/preload.js
The current code that enables Jitsi screen sharing works only with the public Jitsi servers.
This fix uses the preferences field to decide if the js file should be loaded. The default value of the field is the same as the existing string used, so should work fine for public server out of the box.
@RocketChat/desktopapp
=> [FIX] Support On-Premise Jitsi screen sharing

tasks/release.js
Invoking `electron-builder` via its programmatic API forces us to explicitly inform when to publish the release artifacts.
=> [FIX] Release publishing

build/installer.nsh, src/background/autoUpdate.js
[NEW] Allow setup to disable autoupdate
Closes #849 
you can run the installer with the option "/disableAutoUpdates" to disable the update function in rocket.chat (like the windows App Store version)
=> [NEW] Disable autoupdate on windows installer

src/background/menus.js
I wish I could add them both as shortcuts, but it seems to not be supported right on menu, so only doing few workarounds (like listening to global events or duplicating the menu)..
the motivations are:
* <kbd>⌘</kbd> + <kbd>[</kbd> seems to be used by the majority
* <kbd>⌘</kbd> + <kbd>←</kbd> have another behavior if you're on a text field (exactly where you're most of the time on rocket.chat) that is to go the beginning of the line.
=> Change back and forward shortcuts

src/scripts/sidebar.js
If the server url ending with a trailing slash, the favicon is not displayed in the sidebar url :
If I add the server without a trailing slash it works :
=> [FIX] Server icon not displayed on sidebar if server url ending with a trailing slash

src/scripts/events.js
Add additional condition for option "Show on unread" to show Rocket.Chat window
Closes #1003 
The strange behavior of the function `isFocused()` or a bug in it. 
After closing the application to tray (and no to click anywhere), the focus still remains in the application window (`isFocused()` return `True`). If client received a message in this moment then "show on unread" option is not working correctly (No window shown). In this case `isFocused()` returned `True`, but `isVisible()` returned `False`.
If after that we change focus manually (for example click anywhere or go to another window) then function `isFocused()` returned `False` (as expected) and `isVisible()` returned `False` too.  
In order to solve this problem, added an additional condition that handles this …
=> [FIX] Add additional condition for option "Show on unread"

src/public/preload.js
If RocketChat be running with a subdir, A link which contains other subdir contents does not work.
I changed the validation code from a pair of protocol and hostname to ROOT_URL of RocketChat.
=> [FIX] The behavior of clicking links when running RocketChat with subdir.

src/background/windowState.js
The window state (minimized / maximized) does not persist between when I close and reopen the application. I can see the changes reflected in the `window-state-main.json` file but as soon as the application loads those previous values would be overwritten. This is to correctly set the state (window size) on load of the application.
=> [IMPROVE] Fix remember window state on load

src/scripts/servers.js
Closes #1073
Fixes issue described on issue 1073 by extracting credentials and adding them as headers to the `api/info` request under `server.validateHost` function
=> [FIX] Fix for basic-auth servers connect

src/public/update-dialog.html
In 2.15.0 the buttons "Remind me later" and "Install update" will not work for future updates. This is resolved with this fix.
=> [FIX] "Remind me (this update) later" button

src/main.js, src/main/deepLinks.js
This PR aims to make the desktop app partially follow [the spec for Rocket.Chat deep links](https://rocket.chat/docs/developer-guides/deeplink/). Proper authentication and room opening are not implemented yet.
=> [FIX] Deep links handling (incomplete)

appveyor.yml
The steps of writing the code signing certificate into a temporary file and running tests should be at the `build_script` section instead of the `install` one. It's expected that can mitigate the building crash that occurs when a pull request is made.
=> [CHORE] Fix AppVeyor pipeline for pull requests

src/preload/notifications.js
Sometimes the `Content-Type` doesn't match the actual content type on avatars.
=> [IMPROVE] Infer content type for notification icon

src/preload/jitsi.js
Closes #1421
It updates how [`desktopCapturer.getSource`](https://www.electronjs.org/docs/api/desktop-capturer#desktopcapturergetsourcesoptions) is invoked.
=> fix: Screen sharing in Jitsi

electron-builder.json
@RocketChat/frontend
This PR adds the "camera" connection for SnapCraft, which is not added by default from electron-builder.
Without it a user can not use the webcam during video chat, and AFAIK has no way to add it manually.
In addition the user needs to connect the camera manually once:
snap connect rocketchat-desktop:camera
We should probably mention this in the docs as well.
Thoughts?
See:
* https://www.electron.build/configuration/snap
* https://snapcraft.io/docs/supported-interfaces
=> fix: Add snap connection for camera

src/components/TrayIcon.js, src/i18n/en.i18n.json
Adds a balloon to warn that there is an icon in system tray/notification area.
=> fix: Display tray icon balloon when main window is hidden

src/components/App.js, src/main.js, src/sagas/deepLinks.js
It handles both `./electron /path` and `./rocketchat-desktop` CLI invocations.
=> fix: Command line args handling on packaged apps

src/actions.js, src/components/MainWindow/sagas.js, src/components/MenuBar/AppMenu.js, src/main.js, src/preload/userPresence.js
Closes #194 
Sets the user preference to away when the laptop's screen goes blank(sleep), the lid is shut or screen is locked (windows OS)
=> perf: Improve away detection

src/main.js
On macOS, the width is consistent with the web app. 400px for the smallest width is now possible. 
Closes #190
=> fix: Minimum width in split view on OS X is 600px

build/entitlements.mas.plist
> com.apple.security.temporary-exception.files.absolute-path.read-only - Value must be string, or array or dictionary of strings, but contains value "True"
=> fix: Remove wrong entitlements on MAS builds

src/app/actions.ts, src/app/selectors.ts, src/i18n/en.i18n.json, src/navigation/actions.ts, src/navigation/main.ts, src/navigation/reducers.ts, src/store/rootReducer.ts, src/ui/main/dialogs.ts, src/ui/main/webviews.ts
Links not using schemas like `http:`, `https:`, and `mailto:` can spawn unsafe operations when their protocols are associated to external programs. This PR aims to ask for user permission before triggering anything else.
=> fix: Opening links with external protocol

src/ui/main/webviews.ts
Check if URL's protocol in `window.open()` calls is allowed by the user or not.
=> fix: Verify url protocol in window.open

src/ui/main/webviews.ts
Any persistent data (cookies, localStorage etc.) related to a server must be purged when the server is removed.
=> regression: Clear storage data on remove server

src/servers/main.ts
It allows support for servers in the range `>=2.0.0`.
=> fix: Increase server version range

build/entitlements.mas.plist
It removes unused entitlement blocking Mac App Store submission.
=> build(osx): Remove unnecessary MAS entitlement

src/injected.ts
The idleness detection was changing the user's preferred status instead of changing his connection status, this PR calls the correct Meteor method to set the connection status.
=> fix: Set connection status instead of user's default status

src/ui/main/rootWindow.ts
Closes #1590
Closes #1612
`BrowserWindow`'s API doesn't keep "minimized" and "maximized" window states when a hidden window is shown. So, we should forcedly set it again through imperative methods.
=> fix: Recover minimized/maximized state on show window when unread count changes

src/spellChecking/main.ts
- "feat : i18n" 
- "fix:"
Closes #1799
Have set the default language to en-US for the languages unavailable in 
<pre>
session.fromPartition('persist:rocketchat-server').availableSpellCheckerLanguages;
</pre>
Previous Code: 
<pre>
const spellCheckerLanguages = session.defaultSession.getSpellCheckerLanguages();
session.fromPartition('persist:rocketchat-server').setSpellCheckerLanguages(spellCheckerLanguages);
</pre>
Modified code : 
<pre>
const availaibleLanguages = session.fromPartition('persist:rocketchat-server').availableSpellCheckerLanguages;
const defaultSessionLanguage = session.defaultSession.getSpellCheckerLanguages();
const spellCheckerLanguages = availaibleLanguages.includes(defaultSessionLanguage[0]) ? defaultSessionLanguage : ["en-US"]; …
=> fix: Unavailable languages in electron.session()

src/ui/main/trayIcon.ts
The actual fix would be to add a setting to only display this warning
once or never, but for a short term fix this solves the annoying
problem of having a bubble everytime the window is minimized to tray.
Closes #1749
=> fix: Displaying warning every time the window is minimized to tray

.github/workflows/build.yml, .github/workflows/pr-build.yml
Due to https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.
splitting workflows for handling pull requests and pushes would be better to avoiding the accidental usage of encrypted secrets in pull request checks.
=> chore(build): Split workflows for push and pull_request events

src/navigation/main.ts, src/ui/main/serverView/index.ts
Closes #1834
Closes #1841
Closes #1881
Jitsi tries to check if it's running in an Electron view by locating it's version string in user agent string. Due to a previous spoof, this check fails because it expects an `Electron/x.y.z` pattern which is absent. Spoofing the user agent only for Google subdomains will help a little for now.
=> fix: Broken Jitsi's browser check

src/ipc/channels.ts, src/ipc/main.ts, src/ipc/renderer.ts, src/preload.ts, src/ui/main/serverView/index.ts
Probably related to #1919
The current release candidate of Rocket.Chat server renders oEmbed attachments inside sandboxed iframes. The preload script inside them may crash the server view renderer process (which leads to the gray blank page) if the iframe is unloaded while `webFrame.executeJavaScript()` is running. [This may be an Electron regression](https://github.com/electron/electron/pull/22975). As a workaround, we're only using IPC in the preload script to signal the main process to inject code in the server view via `webContents.executeJavaScript()`.
=> fix: Preload script in sandboxed iframes

src/ui/main/trayIcon.ts
Closes #1935 
Revert change from #1700 where focused state was used for window visibility determination.
=> fix: Tray icon toggle action

src/ui/components/SideBar/index.tsx, src/ui/components/SideBar/styles.tsx
**Existing**: We have 2 separate style components for both the buttons, which were redundant, and in case we want to add a new button we will have to add a new component.
**Addition**: New reusable style component for the sidebar action labels, **fixes the existing UI issues of "add server", "download" buttons, considering RC's design standards such as 2px border-radius, etc, also it can be used if we add more such action buttons in the future.**
Closes #1959
=> refactor: Reusable sidebar action's label style component

src/notifications/renderer.ts, src/ui/main/rootWindow.ts
Closes #2043
Closes #2113 
When a new message is received on Linux, the text "Rocket.Chat is read" was appearing instead of the text message, as reported in issue #2043
=> fix: Prevents Notifications on Linux to show the message "Rocket.Chat is ready"

src/servers/main.ts
Closes #1836
After importing the servers.json file and on the first launch of the application, the user was presented with the "enter server url" prompt instead of the first entry in the servers.json. This is a bad experience for organizations.
This really only affects enterprises that want to deploy Rocket.Chat and set servers from servers.json.
This fix assumes the organization would want the first listed server as the default server and really, this is enough to make most organizations happy as they can always deploy a new file with a different order. Unless for some reason, they really need to list the servers in a different order than what they want the default to be. In which case a different fix would be needed to select a default server from the servers.json file.
=> fix: Set default server from serversMap

src/notifications/main.ts
Closes #2091 and #2007.
When a notification arises, if user clicks on that notification, nothing happens. With this fix, it will open relevant chat window (with proper user) as supposed to be.
Tested locally.
=> fix: Notification popup click event does not open relevant chat window.

build/entitlements.mac.plist
originally made to fix https://github.com/RocketChat/Rocket.Chat.Electron/issues/1912
but should also 
fix #1802 
fix #1845 
fix #1965 
fix #1981 
fix #2012 
fix #2132 
fix #2184 
just added a new file which is be used on building the apps: https://www.electron.build/configuration/mac.html
=> fix: missing entitlements on mac app

src/ui/main/menuBar.ts
Fix for https://github.com/RocketChat/Rocket.Chat/issues/23885
Even listeners for two menu items `downloads` and `settings` were not being run async unlike the other items. This resulted in a crash on clicking those menu items. Fixed and verified the fix by running event listeners for both asynchronously.
=> fix: Run menu bar event listeners asynchronously

src/i18n/en.i18n.json, src/i18n/zh-CN.i18n.json, src/i18n/zh-TW.i18n.json, src/ui/main/serverView/popupMenu.ts
Closes #2205
Closes #1279
Closes #1368
A menu item with name 'Copy image' is added in context menu to make it possible to copy images to clipboard. So, it's not necessary to save the image first if you just want to copy it.
=> feat: Add copy image in context menu

electron-builder.json
Closes #2303 
`rpmbuild` generates build_id links by default, which are debugging symbols for binaries included in a package. This causes problems between Electron applications which share the same Electron binary, as the debugging symbols conflict with each other.
By disabling the generation of these links i can verify that i can install the resulting `rpm` package again along with other Electron applications.
See also : 
- https://unix.stackexchange.com/questions/411727/what-is-the-purpose-of-usr-lib-build-id-dir
- https://github.com/rpm-software-management/rpm/blob/rpm-4.18.x/macros.in#L470
- https://github.com/microsoft/vscode/pull/116105
=> Fix: Stop setting build id links for rpm packages

electron-builder.json
**Issue**
---
Rocket.chat installed from Mac App Store(MAS) not handling `rocketchat://` URL scheme
**To Reproduce:**
1. On macOS that never ran Rocket.chat install app from [MAS](https://apps.apple.com/ru/app/rocket-chat/id1086818840?mt=12), launch it
2. Open `rocketchat://invite` in Safari/Chrome
_Expected result:_ Rocket.chat opens
_Actual result:_ Error
**Why is this happening**
---
MacOS applications are required to specify handled protocols inside `Info.plist`
**Electron:**
- https://www.electronjs.org/docs/latest/tutorial/launch-app-from-url-in-another-app#packaging
> When you package your app you'll need to make sure the macOS Info.plist and the Linux .desktop files for the app are updated to include the new protocol handler. Some of the Electron tools for bundling and …
=> Fix: Add "rocketchat://" scheme for macOS application

src/i18n/en.i18n.json, src/ui/components/SettingsView/features/FlashFrame.tsx, src/ui/main/dock.ts, src/ui/main/rootWindow.ts, workspaces/desktop-release-action/dist/index.js
Closes Issue #2463
User was not able to toggle off Dock Bounce in OSX platform for badge alerts, since `Flash Frame` is not an OSX specific feature which was specified in the settings earlier.
1. `Enable Flash Frame` toggle changed to `Toggle Dock Bounce on alert` and the description is changed accordingly
2. Added a constraint for `Flash Frame` for OSX, since `Flash Frame` is not an OSX specific feature
=> feat: toggle dock bounce added for OSX alerts

src/downloads/main.ts, src/i18n/en.i18n.json
Closed #2484
After starting a new download when we cancel the download, we get a notification that the download has finished, which can be misleading.
When the download item triggers the done event, it can have only 3 states `completed`, `cancelled`, `interrupted`. 
Hence, the possible fix would be to show a different notification when the download is not completed i.e. the download is in the above remaining two states.
=> fix: Notification Types for download cancelled & completed added.

src/ui/main/serverView/index.ts
- fixed the bug in the will-download event listener.
- Changed the default behavior of the will-download listener.
- Added custom dialog popup on the listener.
- Handled both the states of the save path dialog.
Closes https://github.com/RocketChat/Rocket.Chat.Electron/issues/2469
=> fix: Added Will-download action on cancel and save

src/downloads/main.ts
Closes #2483
User wasn't able to see changes on UI if the user paused the download first and then cancelled that download. Due to this the user wasn't able to `Remove Item from list` nor `Retry` the download!
Since the `pause` state on a download item after being **cancelled**(or interrupted/completed) doesn't matter, it was hence causing conflicting issues with the UI changes on the cancelled item! 
Hence I've removed the `pause` state on the item after its **cancelled** and updated the state of the item with its current state i.e. in this case **cancelled** using `item.getState()`
=> fix: Paused downloads after cancellation reflect changes on UI

src/downloads/reducers/downloads.ts
Closes #2489
When the user pauses a download and then closes the app, on reopening the app they aren't able to `resume` the download or even `remove the download from list`!
Since in Electron, when the app is closed, automatically the `cancelled` state is triggered by electron for the DownloadItem, but unfortunately due to the abrupt quitting of the app by the user, the `cancelled` state doesn't get updated properly in our data store!
Hence in-order to tackle the above situation, I thought of changing the state of all the downloads (except `completed` ones) to `cancelled` as the app starts and hence I've made the following change:
- When the app is first loaded after the restart i.e. when `APP_SETTINGS_LOADED` is called upon...
- I iterate through all the download items and change their …
=> fix: handled Download states w.r.t Electron across app restarts

src/injected.ts, src/servers/common.ts, src/servers/preload/api.ts, src/servers/preload/serverAllowedRedirects.ts, src/servers/reducers.ts, src/ui/actions.ts, src/ui/main/serverView/index.ts
If the link is redirecting to outside the server URL, it will open on web browser.
This prevents from the chat being replaced with another URL by clicking on a link. Making the server always stick to its server url.
Closes #2499
=> fix: Prevents links to navigate to outside of the server URL

workspaces/desktop-release-action/src/index.ts
Disabled Snapcraft uploading from Github Actions while it doesn't have a fix for gnome-keyring headless.
=> fix: Disable Snapcraft upload

src/ui/components/SettingsView/GeneralTab.tsx, src/ui/components/SettingsView/SettingsView.tsx
Closes #2530  
Fix:SettingsView Added Scrolling By adding Overflow-Y:auto
Screenshots->
Before:
After:
=> FIX #2530 :SettingsView Added Scrolling By adding Overflow-Y:auto

README.md
Added missing quotation mark in the settings table.
=> fix: added missing quotation mark in readme

package.json, src/app/main/app.ts, src/servers/main.ts, src/ui/components/AboutDialog/index.tsx
=> Chore: use electron-builder informations for AppId (#2606)

src/injected.ts
[This PR](https://github.com/RocketChat/Rocket.Chat/pull/28876) internalized `user-presence` package. 
Fixed the import path.
Depends on Rocket.Chat release synced with develop
=> fix: user presence import

src/ui/components/DownloadsManagerView/DownloadItem.tsx
Closes #2630 
The infinite loading animation of the progress bar of the download files is forcefully stopped when the percentage reaches 100. GridFS stored files are not able to provide total file size in the beginning of the download. Which makes the percentage go from NaN to Infinite then finally to 100 when download finishes. But if the percentage is provided correctly from start to finish the loading bar is animated as usual. With this fix it stops animating for all completed ones
=> fix: Force stop animation when download completes (#2630)

src/i18n/en.i18n.json, src/i18n/pt-BR.i18n.json, src/ui/main/dialogs.ts
=> fix: Set the default option to NO in the not trusted certificate dialog

.github/workflows/pull-request-build.yml, electron-builder.json, package.json, yarn.lock
=> Update Electron 31.6.0

src/i18n/main.ts
Added a safety check at the end of the getLng function. This check verifies if translations exist for the language portion of a locale (e.g., 'en' from 'en-US') when the full locale isn't found in the resources object. This prevents errors when translations exist for a base language but not for a specific regional variant.
Demo gif:
Closes #2960
=> fix: Electron i18n language setup

.github/workflows/pull-request-build.yml, package.json, src/ui/components/ServersView/ServerPane.tsx, src/ui/components/ServersView/index.tsx
This PR introduces an optimization to defer the loading of server webviews.
**Changes:**
*   **Conditional Webview Loading:** Server webviews for inactive (not currently selected) tabs will now only have their content loaded if the user is known to be logged in or if their login status is not yet determined. If a server is inactive and the user is known to be logged out, its webview content will not be loaded, saving bandwidth and initial resource usage.
*   **User Experience:** When a user clicks on a server that was previously unloaded due to being logged out, the webview will now load as expected, allowing them to log in.
**Goal:**
The goal is to reduce unnecessary bandwidth consumption and improve performance by avoiding the loading of content for servers that are not actively in use …
=> feat: Optimize server loading by deferring inactive webviews

build/entitlements.mac.plist, build/entitlements.mas.inherit.plist, build/entitlements.mas.plist, electron-builder.json, package.json
=> fix: Add network entitlements

electron-builder.json, package.json, src/ipc/channels.ts, src/videoCallWindow/ipc.ts, src/videoCallWindow/videoCallWindow.tsx
This PR implements automatic detection of Jitsi call termination to close the video call window gracefully. 
- Monitors URL navigation events in the video call webview
- Detects when the URL contains "close" (indicating the call has ended)  
- Automatically triggers the `video-call-window/close-requested` IPC handler
- Properly closes the video call window when Jitsi redirects to a "close" page
- Adds a `did-navigate` event listener to the webview in `videoCallWindow.tsx`
- Implements `checkForClosePage()` function that inspects navigation URLs
- Leverages existing IPC infrastructure (`video-call-window/close-requested`) for clean window closure
- Improves user experience by eliminating manually having to close the video call window
- Prevents orphaned video call windows after Jitsi calls …
=> feat: Close video call window when Jitsi call is closed

alpha-app-update.yml, beta-app-update.yml, src/app/PersistableValues.ts, src/app/selectors.ts, src/i18n/de-DE.i18n.json, src/i18n/en.i18n.json, src/i18n/es.i18n.json, src/i18n/fi.i18n.json, src/i18n/fr.i18n.json, src/i18n/hu.i18n.json, src/i18n/pl.i18n.json, src/i18n/pt-BR.i18n.json, src/i18n/ru.i18n.json, src/store/rootReducer.ts, src/ui/actions.ts, src/ui/components/AboutDialog/index.tsx, src/updates/actions.ts, src/updates/common.ts, src/updates/main.spec.ts, src/updates/main.ts, src/updates/reducers.ts
This PR enables the use of **update channels** for Rocket.Chat Desktop, allowing us to deliver more stable releases through a structured testing process.
Update channels let users choose how they want to receive updates:
- **🟢 Latest (Stable)** - Fully tested, production-ready releases
- **🟡 Beta** - Feature-complete releases ready for final testing  
- **🔴 Alpha** - Early releases with newest features (may have bugs)
Users can switch channels in **Settings → About → Update Channel** and will only receive updates from their chosen channel.
**Note:** Developer mode must be enabled for the update channel selector to appear in the About dialog. Enable it via **Help → Developer Mode** in the menu bar.
Instead of releasing everything directly to stable, we now follow this flow:
1. **Alpha …
=> feat: Alpha and beta update channels

electron-builder.json, src/documentViewer/ipc.ts, src/videoCallWindow/ipc.ts
A regression in v4.5.0 prevents external applications (like Zoom) from launching when users click "Launch Meeting" in video calls. The issue was introduced in PR #2935 where a global `will-navigate` handler was intercepting all navigation attempts, including external protocol links like `zoommtg://`.
- **Fixed document viewer handler**: Added context checks to only intercept navigation for actual PDF viewers, not video call windows
- **Enhanced video call window**: Added proper external protocol handling with `setWindowOpenHandler` and `will-navigate` handlers
- **Added protocol permissions**: Enabled `openExternal` permission for video call windows
- `src/documentViewer/ipc.ts`: Skip interception for video call windows and external protocols
- `src/videoCallWindow/ipc.ts`: Add …
=> fix: Zoom client launch regression in video call windows

build/afterPack.js
This PR removes the special handling that was skipping electron fuses for Mac App Store (MAS) builds and now applies security fuses consistently across all platforms including MAS.
- **Removed MAS skip logic**: Eliminated the conditional check that was bypassing fuse application for MAS builds
- **Unified platform handling**: Now both `darwin` and `mas` builds receive the same security fuses
- **Improved code structure**: Replaced if-else chain with a cleaner switch statement for better maintainability
- **Consistent security posture**: All macOS builds (regular and MAS) now have the same security enhancements
Previously, the build process was skipping electron fuses for MAS builds under the assumption that "App Store has its own integrity validation." However, electron fuses provide …
=> chore: Add flip fuses to all the builds

src/ui/main/menuBar.ts
fix: #2999
-->
Fixes the issue with the zoom-in shortcut (Ctrl +) not working on the Electron desktop app.
- Updated the accelerator for the zoom-in menu item to 'CommandOrControl+='.
This change ensures that the Ctrl + shortcut works as expected, aligning with the behavior of the zoom-out shortcut and the view toolbar.
Verified that the zoom-in shortcut now functions correctly on Windows and macOS.
=> Fix: Zoom-in shortcut (Ctrl +) not working, updated accelerator

build/afterPack.js
As part of our efforts to disable fuses that may bring security issues, I'm disabling 2 fuses - namely, `EnableNodeOptionsEnvironmentVariable` and `EnableNodeCliInspectArguments`. This issue is related to [VLN-137](https://rocketchat.atlassian.net/browse/VLN-137).
[VLN-137]: https://rocketchat.atlassian.net/browse/VLN-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: disable dangerous fuses in `afterPack.js`

build/entitlements.mas.inherit.plist, build/entitlements.mas.plist
This issue is related to [VLN-61](https://rocketchat.atlassian.net/jira/software/c/projects/VLN/boards/194/?selectedIssue=VLN-61). In short, `disable-library-validation` would allow for the loading of unsigned libraries, which may carry security risks in certain scenarios. This PR removes this setting.
[VLN-61]: https://rocketchat.atlassian.net/browse/VLN-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: remove `disable-library-validation` from builder

src/updates/main.ts
This commit modifies the autoUpdater configuration to allow prerelease updates when the update channel is set to 'alpha' or 'beta'. The changes ensure that the application can receive updates from these channels, enhancing the update management process.
=> fix: Enable prerelease updates for alpha and beta channels in autoUpdates

src/ui/main/rootWindow.spec.ts, src/ui/main/rootWindow.ts
This PR modifies the close event listener for the root window to prevent the event from propagating, ensuring that the application can complete its cleanup process before quitting. This change enhances the stability of the application during the window close operation.
Closes #2906
CORE-1152
=> fix: Crashing app on close window when tray icon is disabled on linux

.github/workflows/build-release.yml, .github/workflows/pull-request-build.yml, .github/workflows/validate-pr.yml
Potential fix for [https://github.com/RocketChat/Rocket.Chat.Electron/security/code-scanning/36](https://github.com/RocketChat/Rocket.Chat.Electron/security/code-scanning/36)
To fix the problem, add a `permissions` block to the workflow file `.github/workflows/pull-request-build.yml`. This block should be placed at the top level (recommended) so it applies to all jobs unless overridden. The minimal required permissions for this workflow are:
- `contents: read` (to allow reading repository contents)
- `pull-requests: write` (to allow posting comments to pull requests)
Add the following block after the `name:` and before the `on:` section:
```yaml
permissions:
contents: read
pull-requests: write
```
No additional imports or definitions are needed, as this is a YAML configuration change.
--- …
=> Potential fix for code scanning alert no. 36: Workflow does not contain permissions

src/ui/components/Shell/styles.tsx
Closes #2953
Fix: Prevent Text Selection in WindowDragBar
What does this PR do?
This PR prevents text selection in the WindowDragBar by adding user-select: none;.
It enhances the user experience by ensuring that no unwanted text highlighting occurs when dragging the window.
Changes Made:
Added user-select: none; to WindowDragBar in styles.tsx to prevent unintended text selection.
This ensures a smoother UI experience by eliminating accidental text selection in the draggable area.
Note: I couldn't run the desktop app locally due to setup issues, so I request a maintainer to verify if this fixes the problem. Let me know if any further modifications are needed.
=> Fix: Prevent text selection in WindowDragBar

workspaces/desktop-release-action/dist/index.js, workspaces/desktop-release-action/src/github.ts, workspaces/desktop-release-action/src/index.ts
This commit introduces two new functions: `clearStaleAssets` and `forceCleanOldAssets`. The `clearStaleAssets` function deletes assets not included in the expected list, while `forceCleanOldAssets` removes older assets when the total exceeds a specified limit, ensuring compliance with GitHub's asset constraints. These functions are integrated into the release process to maintain optimal asset management during development and snapshot releases.
=> fix: Add asset management functions for GitHub releases

build/install-kms-cng-provider.ps1, electron-builder.json
The KMS CNG provider installation script was failing on Windows runners with parse errors due to:
1. Emojis in the script causing encoding issues
2. Complex string formatting syntax that PowerShell couldn't parse
```
Unexpected token 'KB' in expression or statement.
Missing closing ')' in expression.
The string is missing the terminator: ".
```
- Replaced all emojis with text indicators:
- ✅ → [SUCCESS]
- ❌ → [ERROR]  
- 📁 → [INFO]
- ⏳ → [WAIT]
- 🔄 → [INFO]
- 🧹 → [INFO]
- 🎉 → [SUCCESS]
- Fixed string formatting by simplifying file size calculations
- Removed complex string interpolation that was causing parse errors
- Script now parses correctly without syntax errors
- All functionality remains the same, just with text indicators instead of emojis
- File size calculations work correctly …
=> fix: Fix PowerShell script encoding issues causing build failures

.github/workflows/powershell-lint.yml, build/install-kms-cng-provider.ps1
- Adds PSScriptAnalyzer workflow to validate PowerShell scripts during CI
- Prevents syntax errors and parsing issues from reaching production
- Runs on all PRs and pushes that modify PowerShell files
During the Windows signing implementation, we encountered multiple PowerShell script parsing errors that broke the build pipeline. These errors (emojis in scripts, string formatting issues) could have been caught earlier with proper linting.
This PR adds automated PowerShell validation to catch such errors before they merge.
- Installs PSScriptAnalyzer on Windows runners
- Scans all `.ps1`, `.psm1`, and `.psd1` files recursively
- Reports any issues found (syntax errors, best practices, etc.)
- Fails the build if problems are detected
The workflow will validate our existing PowerShell script …
=> ci: Add PowerShell linting to prevent script errors

workspaces/desktop-release-action/dist/index.js, workspaces/desktop-release-action/package.json, workspaces/desktop-release-action/src/windows/index.ts, workspaces/desktop-release-action/src/windows/update-yaml-checksums.ts, yarn.lock
- Fixes Windows auto-update failures caused by SHA512 checksum mismatches
- Adds a post-signing step to update `latest.yml` with correct checksums for signed executables
- Ensures auto-update works correctly with signed Windows packages
The Windows auto-update was failing with errors like:
```
Error: sha512 checksum mismatch, expected PgJ/E5Oh6F+KpImx8up7/iX7nnK8Pk0m6hxEX+Try5dYNessJcQot0/3NMC29gv75NlG8N7jzkEGzvQJzUUDCw==, got vnkABYmF/z52Ym63NEXomDGxLrlfqXMokGtbj/p6S9F1GD85VQW+yAw7fT2u9Z6LXYzKHbqIxj8JCvlZ2/3tSA==
```
This happened because:
1. The `latest.yml` file was generated during build with checksums of **unsigned** files
2. Files were then signed **after** building, which changed their content and checksums
3. When users tried to auto-update, the downloaded (signed) files didn't …
=> fix: Update Windows auto-update checksums after signing
