RocketChat/Rocket.Chat.Electron

app/app.html, app/menus.coffee, app/package.json, app/scripts/start.js, app/stylesheets/base.less, app/stylesheets/start-page.css
=> Servers list

app/scripts/start.js
Tries to parse first.  If fails then tries to read it.
=> fixed if localStorage has a string instead of array

app/main.js
I didn't have this file in my checkout so I updated it to this file which looks like the correct one.
=> update icon path to match repo contents

app/scripts/menus.js, app/scripts/sidebar.js, app/stylesheets/start-page.css
=> Add shortcuts to switch servers

app/scripts/preload.js
Closes #121
- Prevent open suggestions from old spellcheck.
- Delay the menu to allow selection of text when opening the context menu.
- Get selection to give suggestions.
- Show 5 suggestions and add a menu to show more suggestions.
=> Improve spellchecker

app/scripts/preload.js
=> Enable multilanguage spell checker; Allow user to set languages.

app/scripts/menus.js, app/scripts/sidebar.js
=> Reload current server instead of all application

app/scripts/menus.js, app/scripts/sidebar.js
=> Open DevTools for active server

app/about.html, app/scripts/menus.js, tasks/build.js
=> Add the "about" panel for windows and linux

resources/linux/app.desktop
"Application;" as a category has been deprecated (it's too generic). See https://specifications.freedesktop.org/menu-spec/latest/apa.html and then https://specifications.freedesktop.org/menu-spec/latest/apas02.html for a list of registered categories.
=> Update Categories according to XDG specs

app/scripts/preload.js
=> fixed ironic spelling error

app/scripts/preload.js, resources/linux/RHEL/app.spec, tasks/release/linux.js
Closes #24 
Tested working on Fedora 24
=> create rpm package - rebased with develop 

README.md
Add channel - for feedback, interactions, and notifications
=> Clarify Electron = Desktop apps, add comm channel

.travis.yml, app/about.html, appveyor.yml
=> Fix version on about window

src/scripts/tray.js
=> Fix try context menu

.travis.yml, scripts/travis-build.sh
=> Travis: Try ubuntu without sudo

src/scripts/tray.js
Closes #298 
I tried to add a simple callback for left mouse clicks on the tray icon to show up the main window. I wasn't able to compile/test the code. Please review it carefully.
=> Added mouse click event handler for tray icon

package.json, src/background/windowState.js
=> Debounce saveState call

src/public/app.html, src/scripts/servers.js, src/scripts/webview.js, src/stylesheets/main.less, src/stylesheets/utils/_loading.import.less
Closes #303 
Shows loading animation while app is working out if a server exists. This stops the server input screen from being shown briefly after launching.
=> Added loading screen before load

package.json
Closes #316
Add option to install as current user in AppData, or for all users in program files. Only asks for UAC if installing for all users.
=> Install for all users or current user for Windows

src/app.js
Closes #290 
Setting user model id as suggested here https://github.com/electron-userland/electron-builder/wiki/NSIS#guid-vs-application-name
=> Set app user model id to improve notifications

build/win/installer.nsh
Closes #292 
Add option to run at startup at the end of Windows installer
=> Run at startup option for Windows

package.json, src/Toaster.js, src/background.custom.js, src/public/notification.html, src/public/preload.js
Closes #297 
Closes #305
Closes #255 
- Improve notification design for Windows 7 and below
- Fix issues with notifications being displayed behind other windows
- Fix issue with multiple windows being created per notification
- Fix issue in regular notifications when clicking it doesn't open app when minimised
- Added ability to click on notifications so it takes you to the correct message
=> Fix issues with Windows 7 notifications and improve design

package.json
=> Downgrade electron-builder from 11.5.1 to 11.4.4

src/scripts/menus.js, src/scripts/tray.js
Closes #318
Closes #322
@RocketChat/core
=> Prevent error from tray when window reloads

src/Toaster.js, src/public/notification.html
- Fix issue with notification resize
- Fix notification height with multiple monitors
- Make it so you can't highlight the text in a notification
These still appear to be problems:
=> Windows notification issues

src/background/certificate.js
Closes #325
Fixes error when loading images with invalid ssl so it no longer replaces the entire webview with the image.
Also only show 1 ssl notification per certificate, rather than loads if loading lots of the same image
=> Fix multiple certificate notifications and replacing webview with image

build/win/installer.nsh, package.json
Closes #326 
Add option to remove user data during uninstall
=> Add option to remove user data on uninstall

.travis.yml, package.json, scripts/travis-build.sh
Update electron build to fix build for PRs.
Now uses productName for install directory, rather than name
=> Fix PR build

src/background.custom.js, src/public/preload.js
Closes #327
Keep user online if they have used their computer in the last 5 mins, rather than only online if they have interacted with the app in the last 5 mins.
=> Keep user online if they are still active on their system

src/scripts/menus.js, src/scripts/tray.js
Closes #74 
Closes #189 
Add option to hide tray icon
=> Add option to hide tray icon

src/public/preload.js
Closes #317 
Open internal links in app, such as the [#support](https://demo.rocket.chat/channel/support) link in the  [#general](https://demo.rocket.chat/channel/general) channel description.
=> Open link in app if internal url

src/scripts/menus.js, src/scripts/tray.js
Closes #247 
Closes #74
Closes #189
- Add option in menu bar for windows and linux to toggle the menu bar. If the menu bar is hidden pressing alt will show the menu bar again as expected.
- Add ability to hide tray icon on mac (#343)
Default behaviour is to show the menu bar, but it will remember your preference on startup.
=> Add option to toggle menu on windows and linux

.eslintignore, src/app.js, src/public/vendor/jquery-3.1.1.js
=> Update jQuery to 3.1.1

README.md
=> Update readme with install issues

.github/ISSUE_TEMPLATE.md
This fixes a few typos in the ISSUE_TEMPLATE file.
=> Fix typos in ISSUE_TEMPLATE

src/scripts/menus.js, src/scripts/menus/app.js, src/scripts/menus/edit.js, src/scripts/menus/help.js, src/scripts/menus/view.js, src/scripts/menus/window.js, src/scripts/servers.js, src/scripts/sidebar.js, src/scripts/start.js, src/scripts/webview.js
Closes #362 
Closes #267 
Load server config from user data directory on first load if it exists.
Organise/Tidy some of the menu code
=> Load server config from file

src/public/lib/SpellCheck.js
Closes #358
Disable multiple language spell check on windows to fix speed issues
=> Fix speed issues with spell check on Windows

src/public/lib/SpellCheck.js
Closes #387
Closes #386 
Fix typo and issue with disabling multi-language spelling on windows to resolve speed issues.
=> Fix speed issues with spellcheck on windows

src/scripts/servers.js
Closes #422
Open server if it already exists when user tries to add it again, rather than just ignoring it.
=> Open host from add new server page if it exists

src/background/autoUpdate.js
Make sure app closes when installing updates, otherwise all windows close, but app does nothing.
=> Make sure app quits on mac on update

src/public/app.html, src/stylesheets/main.less
Fixes https://github.com/RocketChat/Rocket.Chat.Electron/pull/412#issuecomment-291533980
Drag region in red
=> Reduce drag region to fix manual scroll

src/background/autoUpdate.js
Closes #427 
It seems `undefined` is not a valid return value
=> Fix bug on some OS versions on about window, closes #427

src/background.custom.js
Fixes bug when exiting in full screen on mac showing black screen.
=> Fix bug when closing app in fullscreen

dev-app-update.yml, src/background/autoUpdate.js
Closes #449
Read auto update file settings in install location to persist for  all users.
=> Read update settings from install location

src/public/lib/SpellCheck.js
=> Fix bug in spellcheck

src/background.js, src/scripts/servers.js
Fix some issues when opening rocketchat protocol links when the app is closed.
=> [FIX] Rocketchat protocol enhancements

servers.json, src/scripts/menus/help.js, src/scripts/servers.js
Closes #60 
Added option to reset app data, and removed servers.json so it doesn't load the demo instance by default, and fix an issue that was relying on servers.json to be there.
=> [NEW] Add option to reset app data

package.json
=> npm deps update

.github/ISSUE_TEMPLATE.md
Current Behavior and Expected Behavior descriptions were backawards; now they are not.
=> chore(github): fix issue template descriptions

src/public/lib/Notification.js, yarn.lock
=> [FIX] Notifications not opening correct channel on click

src/scripts/menus.js, src/scripts/menus/help.js
Closes #528 
Add help menu to windows and linux to add remove app data feature
=> Add help menu on windows and linux

src/public/app.html, src/scripts/servers.js, src/scripts/start.js
Converts default server from demo.rocket.chat -> open.rocket.chat
=> Convert default connection to open.rocket.chat

src/i18n/lang/en.i18n.json, src/i18n/lang/pt-br.i18n.json, src/public/lib/SpellCheck.js
links should have a new menu item so people can open them
Closes #106
=> context-link: add context for links

src/i18n/lang/en.i18n.json
Makes sense given that the UX features a hover for the 'Create a New Channel' with caps.
=> [FIX] Changed 'Add new server' to 'Add New Server'

package.json, yarn.lock
=> [FIX] Electron security issue

src/public/app.html
Twitter link from app home screen is incorrect. Oops! Fixed with the correct username.
=> [FIX] incorrect Twitter URL

src/stylesheets/main.less
[FIX] main.less option in main.less file (application was not starting with wrong option)
@RocketChat/desktopapp
=> [fix] CSS option in main.less

src/public/lib/Notification.js
Closes #807
This change addresses Electron improperly handling Windows Aero snap features that cause the desktop app to resize and relocate after a notification is clicked.
=> [FIX] Fixed resize/relocate on clicking notification in Windows 10

src/background.custom.js, src/background/autoUpdate.js, src/public/about.html
The code for auto update need some polishment, but for now it does the job.
=> [FIX] Disable auto update in builds for Mac App Store

src/public/preload.js
Related to https://github.com/RocketChat/Rocket.Chat/pull/11193
=> [IMPROVE] Always force download of uploaded files

HISTORY.md
=> [FIX] Add latest releases to HISTORY.md

src/background/windowState.js
=> [FIX] Don't try to save the window state if it's already destroyed

src/background/autoUpdate.js
This pull request aims to replace the expression that evaluates if the app can be updated.
=> [FIX] Conditions to enable update

src/background/mainWindow.js, src/background/windowState.js, yarn.lock
Closes #181
Closes #870 
Closes #871
=> [FIX] Window state errors on save when antivirus software is present

src/scripts/tray.js
[FIX] Toggled tray icon notifications
Show correct notification count on dock while tray icon was "disabled" / not shown.
Closes #855
=> [FIX] Toggled tray icon notifications

yarn.lock
=> [FIX] Tray icon toggle crashes in MacOS

src/i18n/lang/de_DE.i18n.json, src/i18n/lang/en.i18n.json, src/i18n/lang/fr.i18n.json, src/i18n/lang/pt-BR.i18n.json, src/i18n/lang/ru.i18n.json, src/public/lib/SpellCheck.js
=> [NEW] Add copy link in the context menu

README.md
[UPDATE] Documentation to disable Autoupdates
=> [NEW] Documentation to disable Autoupdates

src/background/mainWindow.js
This pull request fixes quitting on close the main window in Linux and Windows.
=> [FIX] Condition to quit on window close

src/background.js
=> [FIX] Show window on second instance running

build/installer.nsh, src/background/autoUpdate.js
This pull request aims to fix some issues commented in #907.
=> [FIX] Disable autoupdates

src/scripts/events.js
=> [FIX] Main window's visibility toggling in tray window

src/background/mainWindow.js, src/scripts/events.js
=> [FIX] Window closing behavior for Linux environments without a system tray

src/background.js, src/background/appData.js, src/i18n/lang/en.i18n.json, src/scripts/servers.js, yarn.lock
=> [FIX] Reset app data under Windows

src/public/lib/SpellCheck.js
=> [FIX] Dictionaries path detection in spell checker

src/background/mainWindow.js
=> [FIX] Main window closing behavior for Linux

yarn.lock
=> [IMPROVE] Node 11 support

package.json, src/background.js, src/background/mainWindow.js, src/background/notifications.js, src/public/lib/Notification.js, src/public/preload.js, yarn.lock
Closes #890
Closes #775
Closes #357
=> [FIX] Notifications redesigned

src/background/notifications.js
=> [FIX] Fallback notifications for Windows 7

src/scripts/servers.js
This pull request aims to speed up `servers.json` loading time by **not** recursively search for it.
=> [FIX] Speed up servers.json loading

src/background/autoUpdate.js, src/public/about.html
=> [FIX] Check for updates response when an error occurs

src/background/notifications.js
=> [FIX] Disable FreeDesktopNotification actions for Unity desktop

yarn.lock
=> [FIX] Remove dependencies related to the npm's event-stream incident

src/public/loading-error.html
Closes #621
Added a countdown that automatically reloads the error page after a given intervall and displays the counter in the reload button.
=> [NEW] Automatic reload on error page

package.json, src/background.js, src/background/windowState.js, yarn.lock
=> [BREAK] Update dependencies

appveyor.yml
=> [CHORE] Disable artifacts collection by AppVeyor

src/scripts/webview.js
=> [FIX] Auto reload server

src/i18n/lang/ja.i18n.json
I updated Japanese translation.
=> [IMPROVE] Updated Japanese translation

package.json, src/background.js, src/background/systemIdleTime.js, src/preload.js, src/preload/events.js, src/preload/userPresence.js, yarn.lock
=> [FIX] Away detection

src/preload/notifications.js
=> [FIX] Reply notifications in MacOS

src/preload/spellchecking.js
=> [FIX] Apply memoization to spell checking

src/preload/links.js
A bug reported by @marceloschmidt.
=> [FIX] Re-enable download links

src/preload/jitsi.js, src/preload/links.js, src/preload/titleChange.js, src/preload/userPresence.js
Preparing for Rocket.Chat Server 1.0
=> Do not require from Meteor packages anymore

package.json, src/preload/jitsi.js, src/preload/links.js, src/preload/rocketChat.js, src/preload/titleChange.js, src/preload/userPresence.js
=> [FIX] Preload scripts compatibility

README.md
=> [CHORE] Fix typos

src/i18n/lang/zh-TW.i18n.json
Add Traditional Chinese translation
=> [NEW] Add Traditional Chinese translation

src/preload/userPresence.js
=> [FIX] Only set user presence as online when auto away detection is disabled

src/main/updates.js, yarn.lock
=> [FIX] Update crashes when host is unreachable

src/preload/spellchecking.js
=> [FIX] Multiple language selection on spellchecking

src/scripts/sidebar.js
=> [FIX] Compute initials for server name on sidebar is broken

appveyor.yml, src/i18n/lang/zh-CN.i18n.json
=> Add Simplified Chinese translation file

appveyor.yml, src/preload/userPresence.js
=> [FIX] Remove missing variable reference

src/scripts/events.js
=> [FIX] "Show window on unread changed" not working

src/scripts/webview.js
=> [FIX] Fix custom oauth login issue (against develop branch)

src/preload/userPresence.js
=> [FIX] powerMonitor API usage

src/public/dialogs/update.html
Update dialog was closed before emitting events.
=> [FIX] Update dialog events

src/preload.js, src/preload/contextMenu.js, src/preload/spellchecking.js, yarn.lock
It removes some warnings on main process.
=> [FIX] Non context-aware native modules

src/main/mainWindow/index.js, src/public/app.html, src/scripts/webview.js
Additionally, it removes `enableBlinkFeatures` for webviews.
=> [FIX] Enable websecurity

package.json, src/preload/notifications.js, yarn.lock
Chromium doesn't accept exporting tainted canvases anymore.
=> [FIX] Fetch avatar images for notifications without CORS

src/preload/notifications.js, src/scripts/events.js, src/scripts/mainWindow.js, src/scripts/menus.js, src/scripts/servers.js
It fixes some window state issues with debounced updates.
=> [FIX] Main window state handling

src/scripts/events.js
=> [IMPROVE] Focus main window on second app instance event

package.json, rollup.config.js, src/errorHandling.js, src/preload/userPresence.js, src/scripts/events.js, yarn.lock
Closes #1408
Closes #1385
Closes #1271
=> [FIX] Preload script issues

yarn.lock
=> [FIX] Windows select boxes

src/i18n/lang/tr-TR.i18n.json
Good news for Turkish Rocket.Chat users :)
=> feat: Turkish language

package.json, yarn.lock
=> chore: Remove sinon

.travis.yml, gulpfile.js, src/components/App.js, src/components/MainWindow/sagas.js, src/components/MenuBar/WindowMenu.js
It fixes bugs spawned when there is no user data yet.
=> regression: Clean state bugs

src/actions.js, src/components/MainWindow/sagas.js, src/components/MenuBar/AppMenu.js, src/main.js
closes #184 
Adds an option in the menu to disable GPU acceleration. When the menu item is clicked it relaunches the application with GPU acceleration disabled.
Menu Item to disable GPU acceleration active
Menu Item to disable GPU acceleration inactive after GPU acceleration has been disabled
=> feat: Added option to disable GPU acceleration

README.md
It does not close any issues. This is an improvement for the documentation.
=> chore: grammar fixes in README

src/i18n/pl.i18n.json
Polish translation. Please include it in future releases.
=> feat: Add Polish translation

src/preload/notifications.js
=> fix: No notification when the avatar icon comes from a relative URL

package.json, src/main/sagas/root.js, src/main/sagas/utils.js, src/main/ui/notifications.js, src/preload.js, src/preload/errors.js, src/preload/notifications.js, yarn.lock
It updates how notifications are handled without the deprecated `remote` module. Also prepares for a future Electron update.
=> perf: Notifications on main process

src/ui/main/menuBar.ts
=> fix: Update documentation link

.travis.yml, appveyor.yml, package.json, yarn.lock
`tslib` is a runtime library for TypeScript that contains all of the TypeScript helper functions.
Closes #1708
=> fix: Missing tslib at runtime

src/ui/main/menuBar.ts, src/ui/main/rootWindow.ts
The whole menu bar has to be recreated on each app state update.
=> fix: Menu bar crashing

src/rootWindow.ts, src/servers/preload/title.ts, src/store/rootReducer.ts, src/ui/actions.ts, src/ui/common.ts, src/ui/main/rootWindow.ts, src/ui/reducers/rootWindowIcon.ts, src/ui/rootWindow/icon.ts
The title says it all. It's not much performant right now as it depends on rendering the icons asynchronously at the renderer process.
=> feat: Use current server's favicon as window/taskbar icon

src/app/main/dev.ts
Fixes issue introduced in #1726
=> regression: Dynamically import chokidar in development mode

rollup.config.js, src/app/main/dev.ts, src/injected.ts, src/notifications/preload.ts, src/preload.ts, src/servers/preload/api.ts
Fixes an issue introduced by #1710
=> regression: Notifications over context bridge

src/ui/main/rootWindow.ts
The bug was introduced by #1720
=> regression: Clear overlay icon when no global badge

src/app/main/app.ts, src/i18n/main.ts, src/main.ts, src/store/index.ts, src/ui/main/dock.ts, src/ui/main/menuBar.ts, src/ui/main/rootWindow.ts, src/ui/main/touchBar.ts, src/ui/main/trayIcon.ts
Not properly releasing some resources was causing a memory leak on process termination.
=> fix: Gracefully exit the app

electron-builder.json, src/ui/main/webviews.ts
Closes #1562
It asks for permission to access camera and microphone on MacOS and updates required connections on Snap build.
=> fix: Media permissions

jest.config.js, src/deepLinks/main.ts, src/preload.ts, src/servers/common.ts, src/servers/main.spec.ts, src/servers/main.ts
=> fix: Server validation

src/app/main/data.ts, src/app/main/persistence.ts, src/main.ts, src/types/electron-reloader.d.ts, src/ui/common.ts, src/ui/main/rootWindow.ts, src/ui/main/webviews.ts, src/ui/reducers/rootWindowState.ts
=> fix: Window state loading

src/ui/main/webviews.ts
=> fix: Add extension filters to save download dialog

src/i18n/pt-BR.i18n.json
=> fix: Update pt-BR.i18n

src/app/main/app.ts, src/deepLinks/main.ts, src/main.ts, src/navigation/main.ts, src/ui/main/dialogs.ts, src/ui/main/menuBar.ts, src/ui/main/rootWindow.ts, src/ui/main/touchBar.ts, src/ui/main/trayIcon.ts, src/ui/main/webviews.ts
=> fix: Asynchronous window state changes

src/servers/main.ts
=> fix: 3.0 Client cannot connect to server on subdirectory

src/servers/main.spec.ts, src/ui/main/icons.spec.ts
=> test: Update specs and test environment

src/navigation/main.ts
=> fix: Remove Electron and Chrome versions from User-Agent header

src/spellChecking/main.spec.ts, src/spellChecking/main.ts
=> fix: Use a function to set spell checker filtered languages

jest.config.js, src/notifications/renderer.ts, src/rootWindow.ts, src/servers/main.spec.ts, src/servers/main.ts, src/servers/renderer.spec.ts, src/servers/renderer.ts
=> fix: Server in subdirectory

src/main.ts
Bugsnag isn't logging errors on renderer process.
=> fix: Bugsnag error reporting

src/injected.ts, src/ipc/channels.ts, src/userPresence/actions.ts, src/userPresence/common.ts, src/userPresence/main.ts, src/userPresence/preload.ts
=> fix: System idle threshold

src/servers/main.ts
=> fix: Select first server on startup

src/ui/preload/messageBox.ts
=> fix: Apply TouchBar formatting button in focused message box

src/ui/components/SideBar/useSorting.tsx
=> fix: Dragging and dropping outside content in servers list

src/updates/common.ts, src/updates/main.spec.ts, src/updates/main.ts
Closes #1856
Reported first at https://github.com/RocketChat/Rocket.Chat.Electron/issues/1788#issuecomment-704005537
=> fix: update.json files ignored

src/deepLinks/main.ts, src/main.ts, src/spellChecking/main.ts, src/ui/actions.ts, src/ui/components/ServersView/ServerPane.tsx, src/ui/main/menuBar.ts, src/ui/main/serverView/index.ts, src/ui/main/serverView/popupMenu.ts, src/ui/main/webviews.ts
Closes #1864
It creates one partition for each server view, allowing to properly purge all data when the server is removed. Additionally, it fixes an invalid call to clear storage data on app window reload.
=> feat: Isolated server view sessions

src/ui/preload/sidebar.ts
=> fix: Apply sidebar padding change on macOS

src/ui/main/rootWindow.ts
Reduce win32 restriction for flashFrame
Maybe I should have an option in the config for this, what do you say?
=> feat: Flash root window on all platforms

src/ui/components/SideBar/styles.tsx
Signed-off-by: tarun8718 <tarunkumar8718@gmail.com>
Closes #1959
***Before:***
***After:***
=> fix: Download button size

src/ui/main/rootWindow.ts, src/ui/main/serverView/index.ts
=> fix: Stop grabbing focus when dom-ready is emitted; and restore window position correctly when x or y is 0

src/i18n/fr.i18n.json
This PR adds missing translations for French. It also corrects some mistakes from existing translations.
=> fix: Missing French translations

README.md
=> docs: Typo in README.md

src/errors.ts, src/preload.ts, src/ui/main/serverView/index.ts, src/userPresence/main.ts, src/userPresence/preload.ts
=> fix: User presence not updating

src/ui/components/AboutDialog/index.tsx
=> fix(about-dialog): About dialog not displaying version

src/preload.ts
=> fix(jitsi): JitsiMeetElectron unavailable on preload script

src/notifications/main.ts
Reverts RocketChat/Rocket.Chat.Electron#2137
=> Revert "fix: Notification popup click event does not open relevant chat window."

src/ui/components/DownloadsManagerView/index.tsx, src/ui/components/SettingsView/SettingsView.tsx, src/ui/components/Shell/styles.tsx, src/ui/main/rootWindow.ts, src/ui/main/serverView/index.ts
=> fix: Multiple issues: Notification, Settings Style

src/i18n/en.i18n.json
Fix wrong i18n translation typo
closes #2127
=> fix: Update error typo

src/errors.ts, src/main.ts
=> fix: Bugsnag

src/ui/components/ServersView/ServerPane.tsx, src/ui/components/ServersView/styles.tsx
=> fix: Oauth popup

src/store/actions.ts, src/store/fsa.ts, src/store/ipc.ts
=> fix: Click Notification 

src/ui/main/serverView/index.ts
=> fix: Fix oauth  again

src/ui/main/serverView/index.ts
=> fix: remove preventDefault from download

src/deepLinks/main.ts
=> fix: Removes rid param/conditional to fix deeplink

src/preload.ts
=> fix: Fix memory leak after navigation

workspaces/desktop-release-action/src/macos.ts
Closes #1875
https://www.electronjs.org/blog/apple-silicon/
https://github.com/electron-userland/electron-builder/issues/5475
https://github.com/electron-userland/electron-builder/pull/5481
=> feat: apple silicon universal support

src/errors.ts
=> fix: Redact info

package.json, src/main.ts, yarn.lock
=> feat: Electron dl for improve download experience

src/i18n/common.ts
=> fix: Prevent invalid range for unit format

src/ui/main/rootWindow.ts
=> fix: Prevent error if can reach the icon

src/deepLinks/main.ts
=> chore: Improve deeplink handler

src/preload.ts
=> fix: Prevent store send messages before the screen is ready

src/app/PersistableValues.ts, src/app/selectors.ts, src/i18n/en.i18n.json, src/injected.ts, src/servers/preload/api.ts, src/servers/preload/internalVideoChatWindow.ts, src/store/rootReducer.ts, src/ui/actions.ts, src/ui/components/SettingsView/SettingsView.tsx, src/ui/components/SettingsView/features/FlashFrame.tsx, src/ui/components/SettingsView/features/InternalVideoChatWindow.tsx, src/ui/components/SettingsView/features/ReportErrors.tsx, src/ui/reducers/isInternalVideoChatWindowEnabled.ts, src/updates/common.ts, src/updates/main.spec.ts, src/updates/main.ts
=> feat: Setting to open video chat on application window or external browser

src/navigation/main.ts, src/ui/main/serverView/index.ts
=> fix: add back desktop version to userAgent string

build/entitlements.mac.plist, src/app/PersistableValues.ts, src/app/selectors.ts, src/i18n/en.i18n.json, src/injected.ts, src/navigation/main.ts, src/servers/preload/api.ts, src/servers/preload/internalVideoChatWindow.ts, src/store/rootReducer.ts, src/ui/actions.ts, src/ui/components/SettingsView/SettingsView.tsx, src/ui/components/SettingsView/features/FlashFrame.tsx, src/ui/components/SettingsView/features/InternalVideoChatWindow.tsx, src/ui/components/SettingsView/features/ReportErrors.tsx, src/ui/main/serverView/index.ts, src/ui/reducers/isInternalVideoChatWindowEnabled.ts, src/updates/common.ts, src/updates/main.spec.ts, src/updates/main.ts
=> feat: Add clear cache and clear storage data options to server

src/ui/components/ServersView/index.tsx, src/ui/components/SideBar/index.tsx, src/ui/components/hooks/useServers.ts
=> fix: Empty screen from a fresh start + servers.json

src/ui/components/hooks/useServers.ts, src/ui/main/menuBar.ts, src/ui/main/rootWindow.ts
=> chore: Windows menubar not showing after update

src/ui/components/ServersView/ServerPane.tsx
=> chore: better did-attach handling

src/preload.ts, src/servers/preload/api.ts
=> chore: improve preload loading

src/app/main/data.ts
Closes #2102
Closes #1746
Closes #2266
=> fix: infinite number (-0) on bounds being saved by some users

electron-builder.json
=> chore: changes the publisherName to match Rocket.chat and not the certificate issuer

src/ui/main/rootWindow.ts, src/ui/main/serverView/index.ts
=> fix: Object has destroyed message

src/ui/main/rootWindow.ts
=> fix: Object has been destroyed on linux

src/injected.ts, src/servers/preload/api.ts, src/ui/main/serverView/index.ts
=> fix: Jitsi screen sharing

src/ui/main/serverView/popupMenu.ts
=> chore: Handle right-click open-link context menu by isProtocolAllowed

package.json, yarn.lock
=> chore: Update electron to 16.0.7

build/notarize.js, package.json, yarn.lock
10x faster and can solve auto-update memory-leak
=> chore: change notarize tool

src/i18n/zh-CN.i18n.json
Added Simplified Chinese translation to menu items, Downloads and Settings.
=> chore: Add Simplified Chinese translation

package.json, src/ipc/channels.ts, src/jitsi/ipc.ts, src/jitsi/preload.ts, src/main.ts, yarn.lock
=> chore: update electron to 17 and fix desktopCapturer breaking changes

src/deepLinks/main.ts, src/ui/main/rootWindow.ts
=> chore: add verification to browserWindow existence

src/app/main/app.ts, src/ui/main/rootWindow.ts
=> fix app quiting on close

src/app/PersistableValues.ts, src/app/selectors.ts, src/navigation/actions.ts, src/navigation/main.ts, src/navigation/reducers.ts, src/store/rootReducer.ts
=> Add not trusted certificates to config.json

src/errors.ts, src/ui/main/menuBar.ts
=> chore: Only initialize bugsnag if reporting is enabled

src/i18n/en.i18n.json, src/i18n/pt-BR.i18n.json, src/ui/main/rootWindow.ts
=> fix: Minimize on close setting didnt take effect

src/ui/main/rootWindow.ts
=> fix: Not maximize window on notification click when was the last state

electron-builder.json, workspaces/desktop-release-action/src/index.ts
rename release files using OS, add zip to windows and separate arch f…iles
=> chore: Improve release files

src/app/main/dev.ts
=> fix: when in development, the userData folder dont cant be created

package.json, src/app/PersistableValues.ts, src/errors.ts, src/i18n/en.i18n.json, src/ui/components/SettingsView/features/ReportErrors.tsx, src/ui/main/serverView/index.ts, yarn.lock
=> Chore:  Disable bugsnag on Mac Apple Store

src/injected.ts, src/preload.ts, src/servers/preload/api.ts, src/ui/components/ServersView/ServerPane.tsx
=> fix: After refresh Notifications and Menu not working properly 

src/updates/main.ts
=> fix: check for updates button on about dialog on windows

README.md, src/app/main/data.ts
=> chore: Create overridden-settings option

README.md, src/app/main/data.ts
=> chore:  Overridden settings can be add to the \Rocket.Chat\Resources\ folder

package.json, yarn.lock
Closes #2404
Closes #2403
Closes #2400
=> chore: Rollback to Electron 17

src/store/fsa.ts, src/ui/components/SelectClientCertificateDialog/index.tsx
=> fix: Certificate selection

src/ui/main/rootWindow.ts
=> Fix: Change setBounds to stop breaking

src/servers/reducers.ts, src/ui/actions.ts, src/ui/components/ServersView/ServerPane.tsx, src/ui/main/serverView/index.ts
=> fix: Add reload after adding listeners to fix Houston page

src/i18n/en.i18n.json, src/i18n/pt-BR.i18n.json, src/ui/main/rootWindow.ts
=> Chore: Change window name with the unread messages number

yarn.lock
Reverts RocketChat/Rocket.Chat.Electron#2407
=> Revert "chore(deps): bump ejs from 3.1.6 to 3.1.7"

src/app/main/data.ts, src/ui/main/rootWindow.ts
=> Fix: Normalize -Infinity number for window position

src/ui/reducers/openDialog.ts, src/updates/main.ts
=> Fix: check for updates button on about screen

src/ui/components/DownloadsManagerView/DownloadItem.tsx, src/ui/components/DownloadsManagerView/index.tsx
=> Fix: downloads list issues

src/ui/main/menuBar.ts
Signed-off-by: tarun8718 <tarunkumar8718@gmail.com>
Closes #1969
=> Adds missing Accelerators

src/downloads/main.ts, src/i18n/en.i18n.json, src/i18n/pt-BR.i18n.json, src/notifications/actions.ts, src/notifications/common.ts, src/notifications/main.ts, src/notifications/preload.ts, src/ui/actions.ts, src/ui/reducers/currentView.ts
=> Chore: Notification when the download is complete

src/injected.ts, src/servers/common.ts, src/servers/main.ts, src/servers/preload/api.ts, src/servers/preload/gitCommitHash.ts, src/servers/reducers.ts, src/ui/actions.ts
=> Chore: Auto clear cache when the gitCommitHash on server changes

src/ui/components/SideBar/index.tsx, src/ui/components/SideBar/styles.tsx
=> Chore: Add selected state to downloads and settings button

src/injected.ts
=> fix: Check server version to handle jitsi window open

src/injected.ts
=> fix: Being stuck on loading after a SAML login

src/ui/main/rootWindow.ts
=> fix: Destroy temp window after rootWindow

electron-builder.json, package.json, src/app/PersistableValues.ts, src/ui/reducers/isAddNewServersEnabled.ts, yarn.lock
=> fix: Add new server on MAS dont shows off

LICENSE
Updated the license year from 2020 to 2022.
=> Fix: Update license year

src/i18n/en.i18n.json, src/i18n/pt-BR.i18n.json, src/servers/preload/serverAllowedRedirects.ts, src/ui/actions.ts, src/ui/components/SettingsView/GeneralTab.tsx, src/ui/components/SettingsView/features/MenuBar.tsx, src/ui/components/SettingsView/features/MinimizeOnClose.tsx, src/ui/components/SettingsView/features/SideBar.tsx, src/ui/components/SettingsView/features/TrayIcon.tsx, src/ui/reducers/isMenuBarEnabled.ts, src/ui/reducers/isSideBarEnabled.ts, src/ui/reducers/isTrayIconEnabled.ts
=> chore: Improve settings panel 

src/injected.ts
=> fix: Jitsi domain validation didnt worked on some servers

src/app/PersistableValues.ts, src/app/selectors.ts, src/store/rootReducer.ts, src/ui/actions.ts, src/ui/main/trayIcon.ts, src/ui/reducers/hasHideOnTrayNotificationShown.ts
=> chore: Add persistence to minimize to tray notification

src/ui/components/ServersView/ServerPane.tsx, src/ui/main/rootWindow.ts
=> fix: setBounds error on startup

src/ui/components/ServersView/ServerPane.tsx
=> fix: Breaking focus() sometimes

src/ui/components/ServersView/ServerPane.tsx
=> fix: Remove replicated dom-ready event happening on Windows

src/ui/main/rootWindow.ts
=> fix: When out of screen, the window will be repositioned

src/ui/components/ServersView/ServerPane.tsx, src/ui/main/menuBar.ts
=> fix: keyboard shortcuts being stuck on chat webview

src/i18n/de-DE.i18n.json
=> chore: Update German translations

README.md, src/servers/main.ts
=> Fix: Add a new folder for servers.json in macOS

src/ui/components/ServersView/ServerPane.tsx
=> fix: Add back the two steps dom-ready

src/ui/main/serverView/index.ts
=> fix: Twitter link previews navigating instead of opening in browser

src/servers/main.ts, src/servers/preload/gitCommitHash.ts, src/ui/actions.ts
=> fix: Stuck in black screen after server update

src/servers/preload/internalVideoChatWindow.ts, src/ui/main/serverView/index.ts
Reference: https://benjamin-altpeter.de/shell-openexternal-dangers/
=> fix: shell.openExternal not validating the URL

package.json, src/injected.ts, src/servers/preload/api.ts, src/servers/preload/clipboard.ts, yarn.lock
=> fix: Copy link not working on Electron v22

package.json, src/app/main/app.ts, src/servers/main.ts, src/servers/preload/internalVideoChatWindow.ts, src/ui/components/AboutDialog/index.tsx
=> Chore: use electron-builder informations for AppId

src/app/main/app.ts, src/i18n/en.i18n.json, src/i18n/pt-BR.i18n.json, src/jitsi/actions.ts, src/jitsi/reducers.ts, src/ui/actions.ts, src/ui/components/SettingsView/GeneralTab.tsx, src/ui/components/SettingsView/features/ClearPermittedScreenCaptureServers.tsx, src/ui/main/dialogs.ts
=> chore: Add clear screen capture permissions button

src/deepLinks/main.ts
=> chore: Implement conference deeplink

src/ipc/channels.ts, src/public/video-call-window.html, src/videoCallWindow/ipc.ts, src/videoCallWindow/screenSharePicker.tsx
=> chore: Check screen recording permission

src/injected.ts
The one referring to `/app/utils` doesn't work anymore. This changes are backward-compatible.
=> fix: Avoid isomorphic barrel imports from Rocket.Chat code

src/injected.ts
Closes #2639
Closes #2640
Closes #2642
=> fix: Notifications, badge and others not working on old server versions

yarn.lock
=> fix: Update yarn.lock

package.json, src/app/main/app.ts, src/deepLinks/main.ts, src/videoCallWindow/ipc.ts
=> chore: Validate deeplinks protocol set in electron-builder.json

src/servers/common.ts, src/servers/preload/api.ts, src/servers/preload/sidebar.ts, src/ui/components/SideBar/styles.tsx
- change selector to get the correct sidebar color to `rcx-sidebar--main`
Depends on [this fix](https://github.com/RocketChat/Rocket.Chat/pull/29070) on Rocket.Chat side to properly work
=> fix: Sidebar color

src/updates/main.ts
=> fix: Auto update on Windows

src/i18n/en.i18n.json, src/i18n/pt-BR.i18n.json, src/ui/components/SettingsView/features/InternalVideoChatWindow.tsx, src/videoCallWindow/ipc.ts
=> chore: make Meet open on browser by default

src/ui/components/ServersView/ServerPane.tsx, src/ui/main/rootWindow.ts
=> fix: WebView not attached to DOM

build/notarize.js
=> fix: Start using notarytool for macOS builds

src/downloads/main.ts, src/ui/main/serverView/index.ts
=> fix: File extensions not showing on in some cases

src/servers/preload/api.ts, src/servers/preload/internalVideoChatWindow.ts
=> fix: Make jitsi open on the old video call window

src/ui/main/serverView/index.ts
=> fix: Downloads duplicated after adding a server back

src/injected.ts, src/ui/components/AddServerView/styles.tsx
=> fix: Fallback `window.require` on injected script

src/injected.ts, src/servers/common.ts, src/servers/preload/api.ts, src/servers/preload/sidebar.ts, src/servers/reducers.ts, src/ui/actions.ts, src/ui/components/SideBar/ServerButton.tsx, src/ui/components/SideBar/customTheme.tsx, src/ui/components/SideBar/index.tsx, src/ui/components/SideBar/styles.tsx
=> feat: Sidebar custom theme

src/injected.ts
=> fix notifications on server 4.8.x

package.json, yarn.lock
=> Update to Electron 24.8.5 patching CVE-2023-5217

src/deepLinks/main.ts
=> add authentication to room deeplink

.vscode/settings.json, src/i18n/en.i18n.json, src/i18n/es.i18n.json, src/i18n/pt-BR.i18n.json, src/servers/supportedVersions/main.ts, src/servers/supportedVersions/types.ts, src/ui/components/ServersView/ServerPane.tsx, src/ui/components/ServersView/UnsupportedServer.tsx
=> chore: Add Spanish translation

src/outlookCalendar/ipc.ts, src/servers/main.ts, src/servers/reducers.ts, src/servers/supportedVersions/main.ts, src/ui/actions.ts, src/ui/components/AddServerView/index.tsx, src/ui/components/ServersView/ServerPane.tsx, src/ui/components/ServersView/UnsupportedServer.tsx, src/ui/components/SupportedVersionDialog/index.tsx, src/ui/main/menuBar.ts, src/urls.ts
It forces refetching the supported server versions whenever the computer goes online. Additionally, it centralizes all internal URLs into a single module for easy maintainance.
=> refactor: Refresh supported versions whenever the app goes online

package.json, yarn.lock
=> fix: Download cancel error

src/ui/main/menuBar.ts
=> fix: Menu actions not working on the second server

src/injected.ts, src/preload.ts
=> Fix: Preload not being started on some cases

package.json, src/main.ts, yarn.lock
=> chore: Update to Electron 29.1.4

src/main.ts, src/outlookCalendar/preload.ts
https://rocketchat.atlassian.net/browse/SUP-580
=> fix: Outlook sync not working in some cases

.github/workflows/pull-request-build.yml, electron-builder.json, package.json, src/ui/main/serverView/index.ts, yarn.lock
=> Update electron 30

src/i18n/en.i18n.json, src/ui/main/menuBar.ts
=> chore: Add menu to open configuration folder

.github/workflows/pull-request-build.yml
=> Pr comments

src/ui/components/SettingsView/SettingsView.tsx
=> fix: Add back button to settings

workspaces/desktop-release-action/dist/index.js, workspaces/desktop-release-action/src/index.ts
=> fix: Add latest-linux.yml to release files

src/servers/supportedVersions/main.ts, src/urls.ts
=> fix: Update api query after 7.0 server version

electron-builder.json, package.json
=> Version 4.1.2

src/urls.ts
=> fix: Supported versions fallback links

src/servers/supportedVersions/main.ts
=> fix: Error getting uniqueId information from server

.github/workflows/pull-request-build.yml, electron-builder.json, package.json, yarn.lock
https://rocketchat.atlassian.net/browse/CORE-1069
=> chore: Upgrade electron-builder 26

.github/workflows/pull-request-build.yml, build/linux/postinst.sh, electron-builder.json, package.json, src/videoCallWindow/ipc.ts, workspaces/desktop-release-action/dist/index.js, workspaces/desktop-release-action/src/index.ts, workspaces/desktop-release-action/src/linux.ts, yarn.lock
=> fix: Linux building issues

src/ui/components/Shell/index.tsx
=> chore: Remove log

src/ui/components/OutlookCredentialsDialog/index.tsx
=> fix: Outlook credentials checkbox alignment

package.json, src/videoCallWindow/ipc.ts
=> fix: Audio linux permission

src/ipc/channels.ts, src/videoCallWindow/ipc.ts, src/videoCallWindow/main/ipc.spec.ts, src/videoCallWindow/video-call-window.tsx
Fixed the translations for the UI not following the OS language as the main window.
CORE-1297
=> fix: UI translations in video call window

src/i18n/resources.ts
Closes #3073 
Add Swedish and Norwegian to resources.ts so that they can be used in the app.
=> Fix: Add Swedish and Norweigan to resources.ts

.claude.md
- Adds `.claude.md` configuration file to guide Claude Code when working with this repository
- File is hidden (starts with `.`) to avoid cluttering the project root
This configuration file helps ensure consistent, high-quality contributions when using Claude Code for development. It includes:
- Essential commands for building, testing, and running the application
- Platform-specific build commands
- Overview of the Electron app structure (main, renderer, preload)
- TypeScript and React conventions
- Redux state management patterns
- Self-documenting code practices
- Mandatory use of Fuselage design system components
- Links to Fuselage documentation and examples
- Git operation guidelines to prevent unwanted commits
- Worktree support for parallel development without disrupting main work …
=> Add .claude.md configuration file for Claude Code
